name: Demicolon CI
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/refjump.yml
      - README.md
jobs:
  docs:
    if: github.ref == 'refs/heads/main'
    name: Pandoc to Vimdoc
    runs-on: ubuntu-latest
    permissions:
      contents: write # git-auto-commit-action needs push permissions
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: demicolon
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: auto generate vimdoc"
          branch: ${{ github.head_ref }}
